### ISSUE TITLE
Hard-coded IP addresses in requests.

### ISSUE THREAD

**Issue by SWHarrison** [1058-Sophia-Gavrila-Forge/Portfolio-Frontend#2]
There are multiple instances of a hard-coded IP address, specifically http://3.236.213.150:8081 in a majority of the components. Additionally, in src/components/education.tsx contains a request to http://localhost:8081.  I cannot find any reference to where the above IP address is from, and I cannot navigate to it in browser.

1.  I recommend changing the http://3.236.213.150:8081 to a variable that is referenced by the components for ease of change if that IP address changes.
2.  I think the localhost request in education.tsx is a holdover from development and should reference a url with a database, likely http://3.236.213.150:8081.

I would also like some clarification on what exactly is at http://3.236.213.150:8081. I think it is an Amazon hosted VM of some sort to serve as a database/backend.

**Comment by MDarmawan** [comment]
After further digging, I am pretty sure the 3.236.213.150 IP address is a now-decommissioned AWS VM that the previous iteration hard-coded. While hard-coding an alternate value would work, it would not be maintainable at all. The connection from the frontend to backend does not work until this is resolved.
