### ISSUE TITLE
remove un-reviewed changes from dev branch

### ISSUE THREAD

**Issue by escalonn** [1058-Sophia-Gavrila-Forge/Portfolio-Frontend#4]
if dev is an integration branch, and one that will be deployed, then this required my review. remove these changes from dev and bring them back in via another PR, if in fact they belong in one PR together

_Originally posted by @escalonn in https://github.com/1058-Sophia-Gavrila-Forge/Portfolio-Frontend/issues/1#issuecomment-881743448_

**Comment by MDarmawan** [comment]
Since the reversion is a PR, do i need to have Nick approve this too?

**Comment by MDarmawan** [comment]
The PR has went through.
